package com.serenityjbehave.grid;

import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'selvav' at '4/26/16 12:30 PM' with Gradle 2.11
 *
 * @author selvav, @date 4/26/16 12:30 PM
 */
public class LibraryTest {
    
}
