/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'selvav' at '6/1/16 2:42 PM' with Gradle 2.11
 *
 * @author selvav, @date 6/1/16 2:42 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
