/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'selvav' at '6/10/16 11:15 AM' with Gradle 2.11
 *
 * @author selvav, @date 6/10/16 11:15 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
