/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'selvav' at '5/17/16 6:39 PM' with Gradle 2.11
 *
 * @author selvav, @date 5/17/16 6:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
