import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'selvav' at '5/4/16 12:27 PM' with Gradle 2.11
 *
 * @author selvav, @date 5/4/16 12:27 PM
 */
public class LibraryTest {
   
}
